
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:food_app/model/iteem.dart';

List populars = [
  {
    "image": "assets/images/pizza.png",
    "is_favorited": true,
    "price": "20.50 Dh",
    "name": "Massage Luxe",
    "description": "Breakfast and Brunch - American - Sandwich",
    "sources": "Egg - Salad",
    "delivery_fee": "1.49 Delivery Fee Dh",
    "rate": "4.3",
    "rate_number": "273"
  },
  {
    "image": "assets/images/pizza.png",
    "is_favorited": false,
    "name": "Greeny Salad",
    "price" : "8.50 Dh",
    "description": "Breakfast aand Brunch - Juice and Smoothies",
    "time": "15-25 Min",
    "delivery_fee": "2.49 Delivery Fee Dh",
    "rate": "4.5",
    "rate_number": "22"
  },
  {
    "image": "assets/images/pizza.png",
    "is_favorited": false,
    "price": "8.50 Dh",
    "name": "Milk Breakfast",
    "description": "Breakfast and Brunch - American - Sandwich",
    "sources": "Egg - Salad",
    "delivery_fee": "1.49 Delivery Fee Dh",
    "rate": "4.3",
    "rate_number": "273"
  },
  {
    "image": "assets/images/pizza.png",
    "is_favorited": false,
    "price": "6.90 Dh",
    "name": "Freshy Salmon",
    "description": "Breakfast and Brunch - Juice and Smoothies",
    "time": "15-25 Min",
    "delivery_fee": "2.49 Delivery Fee Dh",
    "rate": "4.4",
    "rate_number": "22"
  },

];

List categories = [
  {
    "name" : "Bar",
    "icon" : FontAwesomeIcons.wineGlass
  },
  {
    "name" : "Spa",
    "icon" : FontAwesomeIcons.spa
  },
  {
    "name" : "Restaurant",
    "icon" :  FontAwesomeIcons.hamburger
  },
  {
    "name" : "Snack",
    "icon" : FontAwesomeIcons.cookie
  },
  {
    "name" : "Golf",
    "icon" : FontAwesomeIcons.golfBall
  },
];


final List<Item> roomServices = [
  //
  Item(
      image: "assets/images/salade-cesar-1.jpeg",
      is_favorited: false,
      price: "95 Dh",
      name: "Salade César au choix ;Poulet ",
      description: "Caesar salad of your choice served with anchovies’ cream",
      sources: "Caesar salad of your choice served with anchovies’ cream",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/Salade-de-quinoa.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Salade quinoa aux petits condiments ; avocat, gambas",
      description: "Quinoa salad served with avocado & prawns",
      sources: "Quinoa salad served with avocado & prawns",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/Salade-peche.jpg",
      is_favorited: true,
      price: "130 Dh",
      name:
      "Salade pêcheur aux avocats et agrumes (crevettes roses, gambas, calamars,",
      description:
      "Fisherman salad served with avocado & citrus (shrimps, prawns, squid)",
      sources:
      "Fisherman salad served with avocado & citrus (shrimps, prawns, squid)",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tomatesmozzarelle.jpg",
      is_favorited: true,
      price: "85 Dh",
      name: "Salade tomate & Mozzarella di buffala",
      description: "Menthe,Sodacitron vert,sucre de canne",
      sources: "Tomatoes & Mozzarella di buffalo salad",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "80 Dh",
      name: "Assortiment de salades Marocaines et briouates maison",
      description: "jus de citron,Eau gazeuse",
      sources:
      "Assortment of Moroccan salads & savory puff pastries “Briouates”",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/menurest.jpg",
      is_favorited: false,
      price: "90 Dh",
      name: "Pastilla de poulet & amandes ",
      description: "jus de citron,Eau gazeuse",
      sources: "Chicken & almond pastilla",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  //Pates & Risotto/Pasta & Risoto
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Risotto au safran pur, poulet & gambas façon paella",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Saffron flavored risotto with paella style chicken & prawns",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "80 Dh",
      name: "Risotto végétarien",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Vegetarian risotto",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "110 Dh",
      name: "Bolognaise.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Bolognese",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Saumon.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Salmon",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Fruit de mer.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Sea food",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "110 Dh",
      name: "Poulet champignons.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Chicken & Mushroom",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "90 Dh",
      name: "Pesto.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Pesto",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  //Snack menu
  Item(
      image: "assets/images/snack.jpg",
      is_favorited: false,
      price: "95 Dh",
      name: "Cheeseburger,steak haché, oignons caramélisés, champignons, fromage, laitue et tomate .",
      description: "Snack menu",
      sources: "Cheeseburger, minced beef, caramelized onions, mushrooms, cheese, lettuce and tomatoes",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/snack.jpg",
      is_favorited: false,
      price: "85 Dh",
      name: "Chicken burger, poulet pané, laitue, tomates et oignons .",
      description: "Snack menu",
      sources: "Chicken burger: breaded chicken, lettuce, tomatoes and onions",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/snack.jpg",
      is_favorited: false,
      price: "80 Dh",
      name: "Club Sandwich, œuf, laitue, tomate, dinde fumée, poulet .",
      description: "Snack menu",
      sources: "Club Sandwich, Egg, lettuce, tomatoes, smoked turkey and chicken",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/snack.jpg",
      is_favorited: false,
      price: "80 Dh",
      name: "Burrito au poulet, salade verte, cornichons, oignons, fromage.",
      description: "Snack menu",
      sources: "Chicken burrito, lettuce, pickles, onions, cheese",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/snack.jpg",
      is_favorited: false,
      price: "95 Dh",
      name: "Burrito Viande hachée, salade verte, champignons, oignons, fromage.",
      description: "Snack menu",
      sources: "Minced meat burrito, lettuce,mushroom, onions, cheese",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  //Nos pizzas/ Pizzas
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "70 Dh",
      name: "Margarita",
      description: "Nos pizzas/ Pizzas",
      sources: "Margarita",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "100 Dh",
      name: "Fruit de mer, calamars, crevettes, moules",
      description: "Nos pizzas/ Pizzas",
      sources: "Sea food,squid, shrimps, mussels",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "90 Dh",
      name: "Viande hachée, champignons, oignons, poivrons verts",
      description: "Nos pizzas/ Pizzas",
      sources: "Beef: minced beef: mushrooms, onions, green peppers",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "80 Dh",
      name: "Thon oignons ",
      description: "Nos pizzas/ Pizzas",
      sources: "Tuna & onions",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "70 Dh",
      name: "Végétarienne, aubergines, courgettes, poivrons, oignons",
      description: "Nos pizzas/ Pizzas",
      sources: "Vegetarian, eggplant, zucchini, peppers, onions",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "100 Dh",
      name: "Nordique, saumon émietté, crème",
      description: "Nos pizzas/ Pizzas",
      sources: "Nordic, mincedsalmon, cream",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  //Plateau de canapés/ canapés
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Canapé de saumon et son crémeux à l’aneth",
      description: "Plateau de canapés/ canapés",
      sources: "Salmon canapé with dill cream",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Gougère à la sauce mornay",
      description: "Plateau de canapés/ canapés",
      sources: "Cheese gouger",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Rouleau de printemps à la menthe et sa sauce chili ",
      description: "Plateau de canapés/ canapés",
      sources: "Spring rolls, mint chili sauce",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Tartelette Niçois",
      description: "Plateau de canapés/ canapés",
      sources: "Savory tart Niçoise style ",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Brochette de poulet satay ",
      description: "Plateau de canapés/ canapés",
      sources: "Chicken satay skewer",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Brochette de bœuf aux petits épices",
      description: "Plateau de canapés/ canapés",
      sources: "Beef skewer",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Briouates au fromage parfumé",
      description: "Plateau de canapés/ canapés",
      sources: "Cheese savory puff pastry",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Cigare de légumes, khlii et gingembre frais",
      description: "Plateau de canapés/ canapés",
      sources: "Vegetable’s cigar, dried beef meat & fresh ginger",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "200 Dh",
      name: "Gambas concombre et guacamole piquant",
      description: "Plateau de canapés/ canapés",
      sources: "Prawns & cucumber with spicy guacamole",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  //Nos Desserts / Desserts
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Crème brulée safranée.",
      description: "Nos Desserts / Desserts",
      sources: "Saffron flavored crème brulé",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Pain perdu au caramel beurre salé et sa boule de glace vanille",
      description: "Nos Desserts / Desserts",
      sources:
      "Yummy eggy bread served with salted butter caramel &Vanilla ice cream",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Gâteau aux deux chocolats.",
      description: "Nos Desserts / Desserts",
      sources: "Two chocolates cake",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Assiette de fruits frais découpés ",
      description: "Nos Desserts / Desserts",
      sources: "Sliced fresh fruits",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Assortimentde glaces & sorbets",
      description: "Nos Desserts / Desserts",
      sources: "Assortment of ice creams& sherbets",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Assortiment de pâtisseries Marocaines",
      description: "Nos Desserts / Desserts",
      sources: "Assortment of Moroccan pastries",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "65 Dh",
      name: "Biére sans Alcool / Alcohol-free beer",
      description: "Boissons / Drinks",
      sources: "Boissons / Drinks",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "55 Dh",
      name: "Virgin strawberry colada",
      description: "Boissons / Drinks",
      sources:
      "Jus d’ananas, lait de coco, fraise fraiche Pineapple juice, coco milk/fresh strawberry",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "55 Dh",
      name: "Ice tee",
      description: "Boissons / Drinks",
      sources: "Tea earl grey Sucre de canne Earl gray tea & sugar cane",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "55 Dh",
      name: "Ice tee",
      description: "Boissons / Drinks",
      sources: "Boissons / Drinks",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "55 Dh",
      name: "Virgin Mojito",
      description: "Boissons / Drinks",
      sources:
      "Menthe, soda, citron vert, sucre de canne Mint ; soda, green lemon, sugar cane",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "40 Dh",
      name: "Citronnade / Lemonade",
      description: "Boissons / Drinks",
      sources: "Jus de citron, eau gazeuse Lemon juice, sparkling water",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Cocktail vitaminé / Vitamin cocktail
  Item(
      image: "assets/images/cocktail.jpg",
      is_favorited: false,
      price: "40 Dh",
      name: "Cocktail vitaminé / Vitamin cocktail",
      description: "Boissons / Drinks",
      sources: "Pamplemousse, fraise Grapefruit, strawberry",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cocktail.jpg",
      is_favorited: false,
      price: "40 Dh",
      name: "Cocktail vitaminé / Vitamin cocktail",
      description: "Boissons / Drinks",
      sources:
      "Verveine, citron, sucre vanille Verbena, lemon, vanilla sugar",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cocktail.jpg",
      is_favorited: false,
      price: "50 Dh",
      name: "Cocktail vitaminé / Vitamin cocktail",
      description: "Boissons / Drinks",
      sources: "Orange, cannelle, banane Orange, cinnamon, banana",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Jus de fruits frais / fresh juice
  Item(
      image: "assets/images/jus.jpg",
      is_favorited: false,
      price: "30 Dh",
      name: "Jus de fruits frais / fresh juice",
      description: "Boissons / Drinks",
      sources: "Citron / Lemon ",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/jus.jpg",
      is_favorited: false,
      price: "30 Dh",
      name: "Jus de fruits frais / fresh juice",
      description: "Boissons / Drinks",
      sources: "Orange",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/jus.jpg",
      is_favorited: false,
      price: "30 Dh",
      name: "Jus de fruits frais / fresh juice",
      description: "Boissons / Drinks",
      sources: "Pamplemousse   / Grapefruit ",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/jus.jpg",
      is_favorited: false,
      price: "40 Dh",
      name: "Jus de fruits frais / fresh juice",
      description: "Boissons / Drinks",
      sources: "Orange&carotte / Orange & Carrot",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Soda
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Coca-cola",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Coca zéro",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Fanta orange",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Sprite",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Schweppes citron   / Lemon",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Schweppes tonic",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Hawai / Exotic fruits soda",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "POM’S/Apple Soda",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "30 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Burn",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Eaux / Waters
  Item(
      image: "assets/images/water.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Eaux / Waters",
      description: "Boissons / Drinks",
      sources: "Eau plate / Still Water ",
      delivery_fee: "1 L",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/water.jpg",
      is_favorited: false,
      price: "20 Dh",
      name: "Eaux / Waters",
      description: "Boissons / Drinks",
      sources: "Eau plate / Still Water ",
      delivery_fee: "50 cl",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/water.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Eaux / Waters",
      description: "Boissons / Drinks",
      sources: "Eau gazeuse /Sparkling water",
      delivery_fee: "1 L",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/water.jpg",
      is_favorited: false,
      price: "20 Dh",
      name: "Eaux / Waters",
      description: "Boissons / Drinks",
      sources: "Eau gazeuse /Sparkling water",
      delivery_fee: "50 cl",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Eaux / Waters
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Café Espresso",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Café au lait / coffee with milk",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Cappuccino",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Chocolat chaud / Hot Chocolate",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "35 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Café Double Espresso",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Thé vert à la Menthe / Mint tea",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "35 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Thé Tchaba / Tea of your choice",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
];

List<Item> spa = [
  //SOIN DE VISAGE
  //FACIAL TREATEMENT BY BOTANIKA
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "400 Dh",
      name: "Soin hydratant confort /Facial Moisturizing Care ",
      description: "SOIN DE VISAGE",
      sources:
      "Votre peau retrouve toute sa souplesse, sa douceur et sa vitalité, grâce à ce soin nourrissant qui offre aux peaux sèches une hydratation en profondeur.",
      delivery_fee: "",
      rate: "",
      rate_number: "50 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "500 Dh",
      name: "Soin apaisant douceur /Facial alleviating care",
      description: "SOIN DE VISAGE",
      sources:
      "Idéal pour apaiser votre épiderme des agressions quotidiennes, ce soin apaise la peau, la rend plus souple, plus douce, plus fraiche.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "60 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "400 Dh",
      name: "Soin purifiant anti-brillance /purifying anti-shine care",
      description: "SOIN DE VISAGE",
      sources:
      "L’expertise d’un soin puissance 3élimine les impuretés en douceur, diminue les brillances grâce à la régénération cellulaire at adoucit l’épiderme votre peau est nette, fraiche et éclatante de sante.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "50 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "500 Dh",
      name: "Soin purifiant anti-brillance /purifying anti-shine care",
      description: "SOIN DE VISAGE",
      sources:
      "Pour un effet peau neuve, les teinte, des secrets de beauté d’orient, ce rituel de beauté purifie la peau et vous plonge dans la volupté d’un bain aux senteurs d’argan, reconnu pour ses vertus hydratantes et anti-age.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "60 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "600 Dh",
      name: "Soin anti-âge repulpant/ anti-aging & plumping care",
      description: "SOIN DE VISAGE",
      sources:
      "Pour raviver l’éclat des peaux matures, ce soin resculpte les contours du visage, réduit visiblement les rides et atténue les taches votre peau est raffermie, votre teint plus éclatant.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "75 min"),

  //MASSAGES & RITUELS CORS
  //MASSAGE RITUALS BY BOTANIKA
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "300 Dh",
      name: "Dos parfait/ perfect back",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "Une détente immédiate grâce au massage dos parfait qui permet de délier les tensions concentrées au niveau du dos.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "30 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "300 Dh",
      name: "Modelage relaxant / relaxing massage",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "Ce massage alterne les pressions douces et intenses, pour un pur moment de détente et de délassement.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "30 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "500 Dh",
      name: "Modelage relaxant / relaxing massage",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "Ce massage alterne les pressions douces et intenses, pour un pur moment de détente et de délassement.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "50 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "400 Dh",
      name: "Réflexologie plantaire/plantar reflexology",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "Ce traitement ancestral s’appuie sur la cartographie du pied, l’acupression pratiquée sur des points précis permet de soulager des maux spécifiques, de libérer les tensions nerveuses et de reposer le corps, et l’esprit.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "30 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "400 Dh",
      name: "Modelage tonifiant/ tonic body massage",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "En mettant l’accent sur les zones d’accumulation du stress, ce modelage favorise la circulation énergétique, redonne tonicité et souplesse au corps",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "30 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "600 Dh",
      name: "Modelage tonifiant/ tonic body massage",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "En mettant l’accent sur les zones d’accumulation du stress, ce modelage favorise la circulation énergétique, redonne tonicité et souplesse au corps",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "50 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "600 Dh",
      name: "Modelage amincissant raffermissant / slimming massage",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "Modelage amincissant raffermissant par des techniques manuelles spécifiques, ce soin sur-mesure contribue à la réduction de l’effet peau d’orange et de la cellulite en agissant directement sur les tissus adipeux redonnant à la peau toute sa souplesse et son élasticité.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "60 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "600 Dh",
      name: "Message beldi/Traditional beldi massage",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "Pour un véritable voyage des sens terre d’orient, ce massage relaxant aux douces senteurs d’argan vous offre un pur moment de relaxation grâce à un massage des jambes et des bras. ",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "50 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "700 Dh",
      name: "Modelage sensoriel a la bougie/ sensory candle massage",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "Entre la chaleur libérée par la bougie, la volupté des senteurs et la douceur du modelage, ce massage offre une expérience sensorielle sans pareille pour un pur moment de délassement.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "60 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "800 Dh",
      name: "Massage aux pierres chaudes/Hot stones massage",
      description: "MASSAGES & RITUELS CORS",
      sources:
      "De précieuses pierres de basaltes chauffées et appliquées sur le corps diffusent une chaleur intense sur les points de tensions pour permettre une relaxation en profondeur. ",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "60 min"),

  // SIGNARURE HAMMAM
  // HAMMAM BY BOTANIKA
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "100 Dh",
      name: "Hammam simple",
      description: "SIGNARURE HAMMAM",
      sources:
      "Un moment de détente dans un bain de vapeur parfumé pour apaiser le corps et l’esprit ",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "25 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "250 Dh",
      name: "Enveloppement au ghassoul/Moroccan Rhassoul* wrap",
      description: "SIGNARURE HAMMAM",
      sources:
      "Au cœur de ce soin, le ghassoul traditionnel, reconnu pour ses vertus purifiantes et hydratantes et pour finir sur une note fraiche, ce soin offre un savonnage au romarin revitalisant. *The ghassoul is a natural clay extracted from the Atlas Mountains",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "30 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "300 Dh",
      name: "Hammam express",
      description: "SIGNARURE HAMMAM",
      sources:
      "Entre deux rendez-vous profitez d’un hammam traditionnel revisité avec gommage corporal au savon noir à l’eucalyptus et un savonnage parfume, pour un moment de detente express.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "30 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "600 Dh",
      name: "Hammam complet",
      description: "SIGNARURE HAMMAM",
      sources:
      "Offrez-vous le ventable rituel du hammam, avec bain de vapeur aromatise, un gommage traditionnel au savon noir et un masque visage et corps au ghassoul suivi d’un savonnage hyaratant a la preciouse huile d’Argan.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "60 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "750 Dh",
      name: "Hammam royal",
      description: "SIGNARURE HAMMAM",
      sources:
      "Le prestigieux cérémonial du hammam traditionnel est une ode aux secrets de beauté arabes, orchestré pour vous offrir une expérience unique, il débute par un enveloppement de savon noir contrastant l’argan et l’eucalyptus, suivi d’un gommage douceur, d’un soin capillaire au ghassoul et se termine sur un savonnage relaxant au lait parfumé et un modelage beldi aux huiles parfumées, un pur moment d’extase !",
      delivery_fee: "",
      rate: "4.3",
      rate_number: "90 min"),

  //EPILATION
  //WAXING
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "50 Dh",
      name: "Duvet / upper lip",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Sourcils / eyebrows",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "160 Dh",
      name: "Visage / facial",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Aisselles / armpits",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Bras / arms",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Maillot / bikini line ",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "220 Dh",
      name: "Maillot intégral / entire bikini area",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "100 Dh",
      name: "Demi jambes / half legs",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "200 Dh",
      name: "Jambes complètes / whole leg",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "260 Dh",
      name: "Dos ou torse / chest or back",
      description: "EPILATION / WAXING",
      sources: "EPILATION / WAXING",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),

  // ESTHETIQUE
  // COSMETIC TREATEMENTS
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "250 Dh",
      name: "Manucure ",
      description: "ESTHETIQUE / COSMETIC TREATEMENTS",
      sources: "ESTHETIQUE / COSMETIC TREATEMENTS",
      delivery_fee: "",
      rate: "",
      rate_number: "45 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "300 Dh",
      name: "Manucure traditionnelle",
      description: "ESTHETIQUE / COSMETIC TREATEMENTS",
      sources: "ESTHETIQUE / COSMETIC TREATEMENTS",
      delivery_fee: "",
      rate: "",
      rate_number: "45 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "300 Dh",
      name: "Pédicure",
      description: "ESTHETIQUE / COSMETIC TREATEMENTS",
      sources: "ESTHETIQUE / COSMETIC TREATEMENTS",
      delivery_fee: "",
      rate: "",
      rate_number: "45 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "350 Dh",
      name: "Pédicure traditionnelle",
      description: "ESTHETIQUE / COSMETIC TREATEMENTS",
      sources: "ESTHETIQUE / COSMETIC TREATEMENTS",
      delivery_fee: "",
      rate: "",
      rate_number: "45 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "60 Dh",
      name: "Pose vernis / nail paiting",
      description: "ESTHETIQUE / COSMETIC TREATEMENTS",
      sources: "ESTHETIQUE / COSMETIC TREATEMENTS",
      delivery_fee: "",
      rate: "",
      rate_number: "15 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Pose french manicure / french manicure nail painting",
      description: "ESTHETIQUE / COSMETIC TREATEMENTS",
      sources: "ESTHETIQUE / COSMETIC TREATEMENTS",
      delivery_fee: "",
      rate: "",
      rate_number: "20 min"),

  //COIFFURE
  //HAIRDRESSING
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "50 Dh",
      name: "Toushing / Blow dry",
      description: "COIFFURE / HAIRDRESSING",
      sources: "COIFFURE / HAIRDRESSING",
      delivery_fee: "",
      rate: "",
      rate_number: "20 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "100 Dh",
      name: "Brushing cheveux cours / short hair brushing",
      description: "COIFFURE / HAIRDRESSING",
      sources: "COIFFURE / HAIRDRESSING",
      delivery_fee: "",
      rate: "",
      rate_number: "20 min"),
  Item(
      image: "assets/images/spamaaden.jpg",
      is_favorited: false,
      price: "200 Dh",
      name: "Brushing cheveux longs / long haire brushing",
      description: "COIFFURE / HAIRDRESSING",
      sources: "COIFFURE / HAIRDRESSING",
      delivery_fee: "",
      rate: "",
      rate_number: "20 min"),
];

final List<Item> rest = [
  Item(
      image: "assets/images/salade-cesar-1.jpeg",
      is_favorited: false,
      price: "95 Dh",
      name: "Salade César au choix ;Poulet ",
      description: "Caesar salad of your choice served with anchovies’ cream",
      sources: "Caesar salad of your choice served with anchovies’ cream",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/Salade-de-quinoa.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Salade quinoa aux petits condiments ; avocat, gambas",
      description: "Quinoa salad served with avocado & prawns",
      sources: "Quinoa salad served with avocado & prawns",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/Salade-peche.jpg",
      is_favorited: true,
      price: "130 Dh",
      name:
      "Salade pêcheur aux avocats et agrumes (crevettes roses, gambas, calamars,",
      description:
      "Fisherman salad served with avocado & citrus (shrimps, prawns, squid)",
      sources:
      "Fisherman salad served with avocado & citrus (shrimps, prawns, squid)",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tomatesmozzarelle.jpg",
      is_favorited: true,
      price: "85 Dh",
      name: "Salade tomate & Mozzarella di buffala",
      description: "Menthe,Sodacitron vert,sucre de canne",
      sources: "Tomatoes & Mozzarella di buffalo salad",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "80 Dh",
      name: "Assortiment de salades Marocaines et briouates maison",
      description: "jus de citron,Eau gazeuse",
      sources:
      "Assortment of Moroccan salads & savory puff pastries “Briouates”",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "90 Dh",
      name: "Pastilla de poulet & amandes ",
      description: "jus de citron,Eau gazeuse",
      sources: "Chicken & almond pastilla",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),

  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "70 Dh",
      name: "Soupe Harira, œufs dur & dattes",
      description: "jus de citron,Eau gazeuse",
      sources: "Moroccan soup Harira served with hard-boiled egg & dates",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "100 Dh",
      name: "Crème de portobello, Saint jacques, croutons à l’ail ",
      description: "jus de citron,Eau gazeuse",
      sources:
      "Creamy portobello soup served with scallop & garlic croutons ",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "170 Dh",
      name:
      "Cœur de filet de bœuf, pomme de terre écrasée à la provençale, petits légumes glacés	",
      description: "jus de citron,Eau gazeuse",
      sources:
      "Beef tenderloin served with mashed potatoes, glazed vegetables",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "150 Dh",
      name:
      "Côtes d’agneau grillées au romarin, mijoté de légumes de saisons",
      description: "jus de citron,Eau gazeuse",
      sources: "Rosemary flavored Lamb ribs served with vegetables stew",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "120 Dh",
      name: "Blanc de poulet cuit à feu doux, gratin de macaroni",
      description: "jus de citron,Eau gazeuse",
      sources: "Slow-cooked chicken breast served with macaroni gratin",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "210 Dh",
      name: "Magret de canard à la pêche rôtie, sauce aigre douce",
      description: "jus de citron,Eau gazeuse",
      sources:
      "Duck breast flavored with roasted peach, sweet and sour sauce.",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "170 Dh",
      name:
      "Saint pierre de nos côtes, Mhamssa aux petits légumes façon tajine",
      description: "jus de citron,Eau gazeuse",
      sources:
      "John dory filet, served with Mhamssa, tajine style vegetables",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "170 Dh",
      name:
      "Pavé de saumon, mousseline de fenouil, beurre blanc aux agrumes.",
      description: "jus de citron,Eau gazeuse",
      sources:
      "Salmon filet, white butterwith citrus served with fennel foam",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "30 Dh",
      name: "Purée de pomme de terre /Mashed potatoes",
      description: "jus de citron,Eau gazeuse",
      sources: "Accompagnements / side dishes",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "30 Dh",
      name: "Riz basmati safrané/ Saffron flavored Basmati rice",
      description: "jus de citron,Eau gazeuse",
      sources: "Accompagnements / side dishes",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "30 Dh",
      name: "Mijoté de légumes de saison. Seasonal vegetable stew",
      description: "jus de citron,Eau gazeuse",
      sources: "Accompagnements / side dishes",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "30 Dh",
      name: "Pommes frites Maison. Homemade French fries",
      description: "jus de citron,Eau gazeuse",
      sources: "Accompagnements / side dishes",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "30 Dh",
      name:
      "Champignons poêlés aux herbes et à l’échalote. Sauteed mushrooms with herbs & shallots",
      description: "jus de citron,Eau gazeuse",
      sources: "Accompagnements / side dishes",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "95 Dh",
      name:
      "Cheeseburger,steak haché, oignons caramélisés, champignons, fromage, laitue et tomate",
      description: "Côté snacking/ Snacks",
      sources:
      "Cheeseburger, minced beef, caramelized onions, mushrooms, cheese, lettuce and tomatoes",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "85 Dh",
      name: "Chicken burger, poulet pané, laitue, tomates et oignons",
      description: "Côté snacking/ Snacks",
      sources:
      "Chicken burger: breaded chicken, lettuce, tomatoes and onions",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "80 Dh",
      name: "Club Sandwich, œuf, laitue, tomate, dinde fumée, poulet",
      description: "Côté snacking/ Snacks",
      sources:
      "Club Sandwich, Egg, lettuce, tomatoes, smoked turkey and chicken",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "80 Dh",
      name:
      "Burrito au poulet, salade verte, tomate, cornichons, oignons, fromage",
      description: "Côté snacking/ Snacks",
      sources: "Chicken burrito, lettuce, tomatoes, pickles, onions, cheese",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/restmmadenone.png",
      is_favorited: false,
      price: "85 Dh",
      name:
      "Burrito Viande hachée, salade verte, tomate, champignons, oignons, fromage",
      description: "Côté snacking/ Snacks",
      sources:
      "Minced meat burrito, lettuce, tomatoes, mushroom, onions, cheese",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  //Pates & Risotto/Pasta & Risoto
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Risotto au safran pur, poulet & gambas façon paella",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Saffron flavored risotto with paella style chicken & prawns",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "80 Dh",
      name: "Risotto végétarien",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Vegetarian risotto",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "110 Dh",
      name: "Bolognaise.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Bolognese",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Saumon.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Salmon",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Fruit de mer.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Sea food",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "110 Dh",
      name: "Poulet champignons.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Chicken & Mushroom",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pates.jpg",
      is_favorited: false,
      price: "90 Dh",
      name: "Pesto.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Pesto",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Spécialités Marocaines/ Family style Moroccan dishes
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "120 Dh",
      name:
      "Tajine de poulet braisé à l’oignon, citron confit et olives du pays ",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources:
      "Braised chicken tajine served with onions, candied lemon and olives",
      delivery_fee: "1 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "210 Dh",
      name:
      "Tajine de poulet braisé à l’oignon, citron confit et olives du pays ",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources:
      "Braised chicken tajine served with onions, candied lemon and olives",
      delivery_fee: "2 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "380 Dh",
      name:
      "Tajine de poulet braisé à l’oignon, citron confit et olives du pays ",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources:
      "Braised chicken tajine served with onions, candied lemon and olives",
      delivery_fee: "4 Pax",
      rate: "4.3",
      rate_number: ""),

  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "150 Dh",
      name: "La mythique Tanjia de boeufMarrakchia",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources:
      "Beef shank «Tanjia style » slow-cooked with cumin saffron & preserved lemon",
      delivery_fee: "1 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tanjia.jpg",
      is_favorited: false,
      price: "280 Dh",
      name: "La mythique Tanjia de boeufMarrakchia",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources:
      "Beef shank «Tanjia style » slow-cooked with cumin saffron & preserved lemon",
      delivery_fee: "2 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tanjia.jpg",
      is_favorited: false,
      price: "510 Dh",
      name: "La mythique Tanjia de boeufMarrakchia",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources:
      "Beef shank «Tanjia style » slow-cooked with cumin saffron & preserved lemon",
      delivery_fee: "4 Pax",
      rate: "4.3",
      rate_number: ""),

  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "150 Dh",
      name: "Tajine de jarrets de bœufs aux pruneaux caramélisés",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Beef shank tajine served with caramelized prunes",
      delivery_fee: "1 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "280 Dh",
      name: "Tajine de jarrets de bœufs aux pruneaux caramélisés",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Beef shank tajine served with caramelized prunes",
      delivery_fee: "2 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "510 Dh",
      name: "Tajine de jarrets de bœufs aux pruneaux caramélisés",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Beef shank tajine served with caramelized prunes",
      delivery_fee: "4 Pax",
      rate: "4.3",
      rate_number: ""),

  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "150 Dh",
      name: "Tagine d’agneau, artichauts et petit-pois.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Lamb tajine with artichoke and green pea",
      delivery_fee: "1 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "280 Dh",
      name: "Tagine d’agneau, artichauts et petit-pois.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Lamb tajine with artichoke and green pea",
      delivery_fee: "2 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "510 Dh",
      name: "Tagine d’agneau, artichauts et petit-pois.",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Lamb tajine with artichoke and green pea",
      delivery_fee: "4 Pax",
      rate: "4.3",
      rate_number: ""),

  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "140 Dh",
      name: "Tajine Kefta aux oeufs",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Kofta tajine with eggs",
      delivery_fee: "1 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "270 Dh",
      name: "Tajine Kefta aux oeufs",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Kofta tajine with eggs",
      delivery_fee: "2 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/tajine.jpg",
      is_favorited: false,
      price: "500 Dh",
      name: "Tajine Kefta aux oeufs",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Kofta tajine with eggs",
      delivery_fee: "4 Pax",
      rate: "4.3",
      rate_number: ""),

  Item(
      image: "assets/images/couscous.jpg",
      is_favorited: false,
      price: "120 Dh",
      name: "Couscous poulet",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Chicken Couscous",
      delivery_fee: "1 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/couscous.jpg",
      is_favorited: false,
      price: "210 Dh",
      name: "Couscous poulet",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Chicken Couscous",
      delivery_fee: "2 Pax",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/couscous.jpg",
      is_favorited: false,
      price: "380 Dh",
      name: "Couscous poulet",
      description: "Pâtes& Risotto/Pasta& Risotto",
      sources: "Chicken Couscous",
      delivery_fee: "4 Pax",
      rate: "4.3",
      rate_number: ""),

  //Nos pizzas/ Pizzas
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "70 Dh",
      name: "Margarita",
      description: "Nos pizzas/ Pizzas",
      sources: "Margarita",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "100 Dh",
      name: "Fruit de mer, calamars, crevettes, moules",
      description: "Nos pizzas/ Pizzas",
      sources: "Sea food,squid, shrimps, mussels",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "90 Dh",
      name: "Viande hachée, champignons, oignons, poivrons verts",
      description: "Nos pizzas/ Pizzas",
      sources: "Beef: minced beef: mushrooms, onions, green peppers",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "80 Dh",
      name: "Thon oignons ",
      description: "Nos pizzas/ Pizzas",
      sources: "Tuna & onions",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "70 Dh",
      name: "Végétarienne, aubergines, courgettes, poivrons, oignons",
      description: "Nos pizzas/ Pizzas",
      sources: "Vegetarian, eggplant, zucchini, peppers, onions",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/pizza.png",
      is_favorited: false,
      price: "100 Dh",
      name: "Nordique, saumon émietté, crème",
      description: "Nos pizzas/ Pizzas",
      sources: "Nordic, mincedsalmon, cream",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),

  //Nos Desserts / Desserts
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Crème brulée safranée.",
      description: "Nos Desserts / Desserts",
      sources: "Saffron flavored crème brulé",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Pain perdu au caramel beurre salé et sa boule de glace vanille",
      description: "Nos Desserts / Desserts",
      sources:
      "Yummy eggy bread served with salted butter caramel &Vanilla ice cream",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Gâteau aux deux chocolats.",
      description: "Nos Desserts / Desserts",
      sources: "Two chocolates cake",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Assiette de fruits frais découpés ",
      description: "Nos Desserts / Desserts",
      sources: "Sliced fresh fruits",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Assortimentde glaces & sorbets",
      description: "Nos Desserts / Desserts",
      sources: "Assortment of ice creams& sherbets",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/dessert.jpg",
      is_favorited: false,
      price: "70 Dh",
      name: "Assortiment de pâtisseries Marocaines",
      description: "Nos Desserts / Desserts",
      sources: "Assortment of Moroccan pastries",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "65 Dh",
      name: "Biére sans Alcool / Alcohol-free beer",
      description: "Boissons / Drinks",
      sources: "Boissons / Drinks",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "55 Dh",
      name: "Virgin strawberry colada",
      description: "Boissons / Drinks",
      sources:
      "Jus d’ananas, lait de coco, fraise fraiche Pineapple juice, coco milk/fresh strawberry",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "55 Dh",
      name: "Ice tee",
      description: "Boissons / Drinks",
      sources: "Tea earl grey Sucre de canne Earl gray tea & sugar cane",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "55 Dh",
      name: "Ice tee",
      description: "Boissons / Drinks",
      sources: "Boissons / Drinks",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "55 Dh",
      name: "Virgin Mojito",
      description: "Boissons / Drinks",
      sources:
      "Menthe, soda, citron vert, sucre de canne Mint ; soda, green lemon, sugar cane",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/drink.jpg",
      is_favorited: false,
      price: "40 Dh",
      name: "Citronnade / Lemonade",
      description: "Boissons / Drinks",
      sources: "Jus de citron, eau gazeuse Lemon juice, sparkling water",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Cocktail vitaminé / Vitamin cocktail
  Item(
      image: "assets/images/cocktail.jpg",
      is_favorited: false,
      price: "40 Dh",
      name: "Cocktail vitaminé / Vitamin cocktail",
      description: "Boissons / Drinks",
      sources: "Pamplemousse, fraise Grapefruit, strawberry",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cocktail.jpg",
      is_favorited: false,
      price: "40 Dh",
      name: "Cocktail vitaminé / Vitamin cocktail",
      description: "Boissons / Drinks",
      sources:
      "Verveine, citron, sucre vanille Verbena, lemon, vanilla sugar",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cocktail.jpg",
      is_favorited: false,
      price: "50 Dh",
      name: "Cocktail vitaminé / Vitamin cocktail",
      description: "Boissons / Drinks",
      sources: "Orange, cannelle, banane Orange, cinnamon, banana",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Jus de fruits frais / fresh juice
  Item(
      image: "assets/images/jus.jpg",
      is_favorited: false,
      price: "30 Dh",
      name: "Jus de fruits frais / fresh juice",
      description: "Boissons / Drinks",
      sources: "Citron / Lemon ",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/jus.jpg",
      is_favorited: false,
      price: "30 Dh",
      name: "Jus de fruits frais / fresh juice",
      description: "Boissons / Drinks",
      sources: "Orange",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/jus.jpg",
      is_favorited: false,
      price: "30 Dh",
      name: "Jus de fruits frais / fresh juice",
      description: "Boissons / Drinks",
      sources: "Pamplemousse   / Grapefruit ",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/jus.jpg",
      is_favorited: false,
      price: "40 Dh",
      name: "Jus de fruits frais / fresh juice",
      description: "Boissons / Drinks",
      sources: "Orange&carotte / Orange & Carrot",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Soda
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Coca-cola",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Coca zéro",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Fanta orange",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Sprite",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Schweppes citron   / Lemon",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Schweppes tonic",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Hawai / Exotic fruits soda",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "POM’S/Apple Soda",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/soda.jpg",
      is_favorited: false,
      price: "30 Dh",
      name: "Sodas",
      description: "Boissons / Drinks",
      sources: "Burn",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Eaux / Waters
  Item(
      image: "assets/images/water.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Eaux / Waters",
      description: "Boissons / Drinks",
      sources: "Eau plate / Still Water ",
      delivery_fee: "1 L",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/water.jpg",
      is_favorited: false,
      price: "20 Dh",
      name: "Eaux / Waters",
      description: "Boissons / Drinks",
      sources: "Eau plate / Still Water ",
      delivery_fee: "50 cl",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/water.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Eaux / Waters",
      description: "Boissons / Drinks",
      sources: "Eau gazeuse /Sparkling water",
      delivery_fee: "1 L",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/water.jpg",
      is_favorited: false,
      price: "20 Dh",
      name: "Eaux / Waters",
      description: "Boissons / Drinks",
      sources: "Eau gazeuse /Sparkling water",
      delivery_fee: "50 cl",
      rate: "4.3",
      rate_number: ""),
  // Boissons / Drinks
  // Eaux / Waters
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Café Espresso",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Café au lait / coffee with milk",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Cappuccino",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Chocolat chaud / Hot Chocolate",
      delivery_fee: "",
      rate: "",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "35 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Café Double Espresso",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "25 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Thé vert à la Menthe / Mint tea",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
  Item(
      image: "assets/images/cafe.jpg",
      is_favorited: false,
      price: "35 Dh",
      name: "Boissons chaudes / hot drinks",
      description: "Boissons / Drinks",
      sources: "Thé Tchaba / Tea of your choice",
      delivery_fee: "",
      rate: "4.3",
      rate_number: ""),
];











List selectedItems = [

  {
    "image": "assets/images/menurest.jpg",
    "is_favorited": false,
    "price": "40 Dh",
    "name": "Citronnade",
    "description": "jus de citron,Eau gazeuse",
    "sources": "",
    "delivery_fee": "1.49 Delivery Fee Dh",
    "rate": "4.3",
    "rate_number": "273"
  },

];